{% set name = "ena-upload-cli" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7b3602cc7dd35a2112cdf2090d3c476d082560e98feafa3257e1bd40d69a4c1e

build:
  number: 0
  entry_points:
    - ena-upload-cli = ena_upload:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - genshi
    - lxml
    - pandas
    - pip
    - python
  run:
    - genshi
    - lxml
    - pandas
    - python

test:
  commands:
    - ena-upload-cli --help

about:
  home: "https://github.com/usegalaxy-eu/ena-upload-cli"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Command Line Interface to upload data to the European Nucleotide Archive"

extra:
  recipe-maintainers:
    - bedroesb
    - bgruening
    - dyusuf
