package:
  name: kissplice
  version: '2.5.2'

source:
  url: "ftp://pbil.univ-lyon1.fr/pub/logiciel/kissplice/download/kissplice-2.5.2.tar.gz"
  sha256: "caf39b570ab87af2001946ac593947cb015c1cbfea70b115d7939b3c3cd9438b"

build:
  number: 0
  skip: True # [osx or py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python
  run:
    - python

test:
  commands:
    - kissplice -h

about:
  home: http://kissplice.prabi.fr
  license: CeCILL license
  summary: A local transcriptome assembler for SNPs, indels and AS events
